#!/bin/bash

calculate_sum () {
  local num1=$1 # Declare num1 as a local variable
  local num2=$2 # Declare num2 as a local variable
  local sum=$((num1 + num2))
  echo $sum # Functions typically return values by printing them to stdout
}

clone() {
    local repo=$1
    local target_dir=$SPIKES_DIR  # Default to spikes
    
    # Ask where to put it
    echo "Clone to: [s]pikes (default), [p]ersonal, [w]ork, [f]orks?"
    read -n 1 -r choice
    echo
    
    case $choice in
        p) target_dir="$CODE_DIR/personal" ;;
        w) target_dir="$CODE_DIR/work" ;;
        f) target_dir="$CODE_DIR/forks" ;;
        *) target_dir="$SPIKES_DIR" ;;
    esac
    
    cd "$target_dir"
    git clone "$repo"
    cd "$(basename "$repo" .git)"
}

proj() {
    local dir=$(find $CODE_DIR -maxdepth 2 -type d | fzf)
    [ -n "$dir" ] && cd "$dir"
}