---
# Headscale Configuration
# This config will be copied to /etc/headscale/config.yaml by setup-headscale.sh

# The url clients will connect to (replace with your domain)
# For production, use: https://your-domain.com:443
server_url: http://0.0.0.0:8080

# Address to listen to / bind to on the server
listen_addr: 0.0.0.0:8080

# Address to listen to /metrics and /debug
metrics_listen_addr: 127.0.0.1:9090

# Address to listen for gRPC (headscale CLI control)
grpc_listen_addr: 127.0.0.1:50443
grpc_allow_insecure: false

# Noise protocol configuration
noise:
  private_key_path: /var/lib/headscale/noise_private.key

# IP prefixes for tailnet addresses
prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
  allocation: sequential

# DERP relay configuration
derp:
  server:
    # Embedded DERP server (requires HTTPS for server_url)
    enabled: false
    region_id: 999
    region_code: "headscale"
    region_name: "Headscale Embedded DERP"
    stun_listen_addr: "0.0.0.0:3478"
    private_key_path: /var/lib/headscale/derp_server_private.key
    automatically_add_embedded_derp_region: true

  # Use Tailscale's public DERP servers
  urls:
    - https://controlplane.tailscale.com/derpmap/default

  paths: []
  auto_update_enabled: true
  update_frequency: 24h

disable_check_updates: false
ephemeral_node_inactivity_timeout: 30m

# Database configuration (SQLite recommended)
database:
  type: sqlite
  debug: false

  gorm:
    prepare_stmt: true
    parameterized_queries: true
    skip_err_record_not_found: true
    slow_threshold: 1000

  sqlite:
    path: /var/lib/headscale/db.sqlite
    write_ahead_log: true
    wal_autocheckpoint: 1000

# TLS configuration (Let's Encrypt)
acme_url: https://acme-v02.api.letsencrypt.org/directory
acme_email: ""
tls_letsencrypt_hostname: ""
tls_letsencrypt_cache_dir: /var/lib/headscale/cache
tls_letsencrypt_challenge_type: HTTP-01
tls_letsencrypt_listen: ":http"

# Custom TLS certificates (if not using Let's Encrypt)
tls_cert_path: ""
tls_key_path: ""

# Logging
log:
  format: text
  level: info

# ACL Policy
policy:
  mode: file
  path: ""

# DNS configuration
dns:
  magic_dns: true
  base_domain: headscale.local
  override_local_dns: false

  nameservers:
    global:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001

    split: {}

  search_domains: []
  extra_records: []

# Unix socket for CLI access
unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"

# Logtail (disabled - would send logs to Tailscale Inc)
logtail:
  enabled: false

# Randomize client WireGuard port (workaround for buggy firewalls)
randomize_client_port: false
